[program:locknear-horizon]
process_name=%(program_name)s
command=php /var/www/locknear/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/locknear/storage/logs/horizon.log
stopwaitsecs=3600

[program:locknear-reverb]
process_name=%(program_name)s
command=php /var/www/locknear/artisan reverb:start
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/locknear/storage/logs/reverb.log

[program:locknear-scheduler]
process_name=%(program_name)s
command=/bin/bash -c "while [ true ]; do php /var/www/locknear/artisan schedule:run --verbose --no-interaction; sleep 60; done"
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/locknear/storage/logs/scheduler.log
